### ISSUE TITLE
Are we capturing all of the e coli strains?

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#105]
e.g. https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=562

Some observations lately:
  
1. All the top NCBI genes for E coli  (83333) are failing because the ids seem to have been deprecated
2. I would have expected all genes with same name from E coli to have one record, but this doesn't seem to be the case e.g. 

- POST `/search` with  `{ "q": "ssb" }`
  - [ssb for Escherichia coli K12 (taxonid=511145)](https://www.ncbi.nlm.nih.gov/gene/?term=948570)  - not found
  - [ssb in Escherichia coli (taxonid=562)](https://www.ncbi.nlm.nih.gov/gene/?term=59686496%5Buid%5D) - not found
  - [ssb in Escherichia coli O157:H7 str. Sakai (taxonid=386585)](https://www.ncbi.nlm.nih.gov/gene/?term=1789738) - rank 4

**Comment by jvwong** [comment]
@metincansiper Do you remember if we 'merge' genes with the same name from different strains?

**Comment by metincansiper** [comment]
@jvwong we initially attempted to make a merge at index time as in this issue (https://github.com/PathwayCommons/grounding-search/issues/38). However, then we end up with disabling that merge in index time by commenting out the code here (https://github.com/PathwayCommons/grounding-search/blob/master/src/server/datasource/ncbi.js#L168). 

@maxkfranz did you make an implementation to do a merge in search time instead of index time?

**Comment by maxkfranz** [comment]
It would be at search time, and it wouldn't strictly be a merge. I think there's just an organism grouping. If a search has more than one result from organisms that are grouped (e.g. strains), then only the first result from the group is included in the search result.

**Comment by jvwong** [comment]
OK I don't want to get bogged down in this. Its just that it makes it hard to test (which gene ID do I use?). Anyways, we'll reopen if it becomes a real issue.
