### ISSUE TITLE
Datasource tests failing

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/grounding-search#15]
@metincansiper 

The datasource import tests are failing.  See https://travis-ci.org/PathwayCommons/grounding-search/jobs/526196412

ID handling has been improved so any hardcoded Chebi IDs need to be updated in the tests.  Chebi IDs that are formatted like 'CHEBI:123' should just use `{ namespace: 'chebi', id: '123' }` from now on.  The `_id` is now `CHEBI:123` or `NCBI:456`.

It looks like some other tests for the datasources are failing for reasons unknown to me.  Maybe the tests are too strict / brittle?  They shouldn't check for deep equality on the element JSON, for example.

**Comment by maxkfranz** [comment]
The aggregate quality tests are passing, so I suspect that the datasource tests are false positives.

**Comment by metincansiper** [comment]
I actually solved the problems related to this issue by teh commit https://github.com/PathwayCommons/grounding-search/commit/b95be41ec42ae3cf602665ea807647b38dfa0abb

However, now quality tests are failing since [quality search data](https://github.com/PathwayCommons/grounding-search/tree/master/test/util/data) is updated. Now, I am working updating input generator code to be able to generate sample input test files that covers new search data. However, I need to make some changes as the last search data includes a lot of genes and the older input generator files are failing for that size.

**Comment by maxkfranz** [comment]
Don't worry about the sample test data for now.  We'll have to test on the full data set to be certain we're improving things in practice.  Once that's been sorted out, we can update the sample data.

**Comment by metincansiper** [comment]
Okay but I already made some uncommitted changes about that I just committed them (4c7fb5a818a4884be091d62c5775d66186f9d814). I was planning to add tests for input generator, then I am postponing it.
